# Unique project key
sonar.projectKey=nodejs-devops-app

# Project name
sonar.projectName=NodeJS DevOps CI/CD App

# Version
sonar.projectVersion=1.0

# Source directory
sonar.sources=.

# Language
sonar.language=js

# Encoding
sonar.sourceEncoding=UTF-8

# Exclude node_modules
sonar.exclusions=node_modules/**

# Optional test coverage path (if added later)
# sonar.javascript.lcov.reportPaths=coverage/lcov.info
